// public/lang/ko.js

// UI 관련 텍스트
export const UI_TEXT = {
    loading: "로딩중...",
    suggestReplies: "응답 제안",
    analyzeSentence: "문장 분석",
    errorMessageSuggestions: "적절한 제안을 찾지 못했어요.",
    errorMessageAnalysis: "분석 오류:",
    noUserMessageForAnalysis: "분석할 사용자 메시지가 없습니다.",
    suggestionsAfterAiResponse: "AI의 응답 후에만 제안을 요청할 수 있습니다.",
    aiResponseError: "AI 응답 오류:",
    newConversationAlert: (scenarioTitle) => `"${scenarioTitle}" 시나리오로 새 대화를 시작합니다.`,
    roleChangeAlert: (roleDescription) => `역할이 변경되었습니다! 이제 당신은 "${roleDescription}"입니다. AI가 먼저 말을 걸도록 하거나, 새로운 역할에 맞춰 대화를 시작해보세요.`,
    scenarioChangeLoadingAlert: "AI가 응답 중일 때는 시나리오를 변경할 수 없습니다.",
    newConversationLoadingAlert: "AI가 응답 중일 때는 새 대화를 시작할 수 없습니다.",
    customScenarioInputRequired: "사용자 정의 시나리오 내용을 먼저 입력해주세요.",
    customScenarioPlaceholder: "연습하고 싶은 상황이나 대화 주제를 자세히 입력해주세요...",
    focusTopicPlaceholder: "집중 연습 주제 (선택 사항)",
    scenarioTitleCustom: (input) => input ? `주제: ${input.substring(0, 40)}...` : "사용자 설정 시나리오",
    customScenarioDescription: "연습하고 싶은 상황이나 주제를 아래에 자세히 입력해주세요.",
    starterPhrasePrefix: "이렇게 시작해 보세요:",
    aiReplySuggestionsPrefix: "AI 응답 제안:",
    analysisResultTitle: "✨ 내 문장 분석 결과",
    englishFeedbackTitle: "📝 영어 피드백:",
    koreanSummaryTitle: "🇰🇷 한국어 요약:",
    analysisConfirmButton: "확인했어요!",
    guideModalTitle: "SpeakUp AI 사용 가이드 🚀",
    guideModalConfirmButton: "알겠습니다!",
};

// 시나리오 데이터
export const SCENARIO_DATA = [
    { category: "일상 생활 (Everyday Life)", items: [
        { id: "cafe", title: "카페에서 주문하기 ☕", description: "바리스타에게 커피를 주문하고 간단한 요청을 해보세요. AI는 친절한 바리스타 역할을 합니다.",
          baseContext: "You are a friendly barista. The user is ordering coffee. Respond concisely (1-2 sentences), ask one question at a time if necessary, and assist with their order. Do not ask questions you've already received answers for.",
          baseContext_swapped: "You are a customer ordering coffee. The user is the barista. Make your order and ask any questions you might have. Keep your requests concise.",
          starters_userAsPrimary: ["Hi, can I get a latte?", "Hello! What do you recommend?", "I'd like to order a coffee, please."],
          starters_userAsOther: ["Hi there! What can I get for you today?", "Welcome! Ready to order?", "Hello! How can I help you?"] },
        { id: "grocery_shopping", title: "식료품점에서 장보기 🛒", description: "점원에게 물건 위치를 묻거나 계산할 때 대화해보세요. AI는 친절한 점원 역할을 합니다.",
          baseContext: "You are a helpful grocery store clerk. The user is shopping. Respond concisely (1-2 sentences) and help them find items or checkout. Ask one question at a time if needed. Do not ask questions you've already received answers for.",
          baseContext_swapped: "You are a customer at a grocery store. The user is the clerk. Ask for help or proceed to checkout concisely.",
          starters_userAsPrimary: ["Excuse me, where can I find the milk?", "How much is this?", "I'd like to pay for these items."],
          starters_userAsOther: ["Hi! Can I help you find something?", "Are you ready to check out?", "Did you find everything okay?"] },
        { id: "making_appointments", title: "예약하기 (미용실, 병원 등) 🗓️", description: "전화나 방문을 통해 예약하는 상황을 연습합니다. AI는 접수원 역할을 합니다.",
          baseContext: "You are a receptionist at a salon/clinic. The user wants to make an appointment. Guide them concisely (1-2 sentences per turn), asking one question at a time for preferences and confirming details. Do not ask questions you've already received answers for.",
          baseContext_swapped: "You want to make an appointment. The user is the receptionist. State your needs concisely.",
          starters_userAsPrimary: ["I'd like to make an appointment for a haircut.", "Do you have any openings next Tuesday?", "Can I book a check-up for this week?"],
          starters_userAsOther: ["Hello, [Salon/Clinic Name], how can I help you?", "Good morning! How may I assist you with scheduling?", "Are you looking to book an appointment?"] },
        { id: "daily_routine_talk", title: "일상 이야기하기 ☀️", description: "하루 일과나 주말 계획 등 일상적인 주제로 대화합니다. AI는 친구 역할을 합니다.",
          baseContext: "You are a friend. The user wants to talk about daily life. Engage in a casual, concise (1-2 sentences per turn) conversation. Ask one question at a time if needed. Do not ask questions you've already received answers for.",
          baseContext_swapped: "You are talking to a friend (the user). Share something about your day or ask about theirs, keeping it concise.",
          starters_userAsPrimary: ["How was your day?", "What are you up to this weekend?", "I usually [activity] in the morning."],
          starters_userAsOther: ["Hey! What's new?", "How's it going?", "Anything interesting happen today?"] },
        { id: "public_transportation", title: "대중교통 이용하기 🚌", description: "버스나 지하철 표를 사거나 길을 묻는 상황입니다. AI는 역무원 또는 다른 승객 역할을 합니다.",
          baseContext: "You are a public transport staff or a helpful passenger. The user needs help. Provide clear, concise (1-2 sentences per turn) assistance. Ask one question at a time if needed. Do not ask questions you've already received answers for.",
          baseContext_swapped: "You need help with public transport. The user is staff/passenger. Ask your question concisely.",
          starters_userAsPrimary: ["Which bus goes to downtown?", "How much is a single ride ticket?", "Is this the platform for the express train?"],
          starters_userAsOther: ["Can I help you with something?", "Are you looking for a specific line?", "Tickets can be purchased over there."] }
    ]},
    { category: "여행 (Travel)", items: [
        { id: "airport_checkin", title: "공항 체크인 ✈️", description: "공항 체크인 카운터에서 탑승 수속을 진행합니다.", baseContext: "You are an airline check-in agent. The user is checking in for a flight. Ask for passport/ticket, discuss baggage, seat preferences. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are at the airport checking in for your flight. The user is the check-in agent. Provide your documents and discuss your flight details concisely.", starters_userAsPrimary: ["I'd like to check in for my flight to London.", "Here's my passport and ticket.", "Can I have a window seat, please?"], starters_userAsOther: ["Good [morning/afternoon/evening]! May I see your passport and ticket, please?", "Where are you flying to today?", "Do you have any bags to check in?"] },
        { id: "hotel_checkin", title: "호텔 체크인 🏨", description: "호텔 프론트에서 예약 확인 및 체크인을 합니다.", baseContext: "You are a hotel receptionist. The user is checking in. Confirm reservation, explain amenities, answer questions. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are checking into a hotel. The user is the receptionist. Provide your reservation details and ask any necessary questions concisely.", starters_userAsPrimary: ["I have a reservation under the name [Your Name].", "Could you tell me what time breakfast is served?", "Is there Wi-Fi in the room?"], starters_userAsOther: ["Welcome to our hotel! How can I help you?", "Do you have a reservation with us?", "May I have your name, please?"] },
        { id: "asking_directions", title: "길 묻기 🗺️", description: "여행 중 모르는 곳에서 길을 묻는 상황입니다.", baseContext: "You are a local resident. The user is a tourist asking for directions. Provide clear, concise (1-2 sentences) instructions and be helpful. Ask one question at a time if needed.", baseContext_swapped:"You are a tourist asking for directions. The user is a local resident. Ask for help finding your way concisely.", starters_userAsPrimary: ["Excuse me, how can I get to the museum?", "Could you show me on the map?", "Is this the right way to the train station?"], starters_userAsOther: ["Yes, how can I help you?", "Where are you trying to go?", "Sure, I can help with that."] },
        { id: "ordering_at_restaurant_travel", title: "여행 중 식당 주문 🍽️", description: "여행지 식당에서 음식을 주문하고 현지 음식에 대해 질문합니다.", baseContext: "You are a waiter/waitress in a tourist-friendly restaurant. The user is ordering food and might ask about local specialties. Be patient and helpful. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are a customer at a restaurant in a tourist area. The user is the waiter/waitress. Order food and ask about the menu concisely.", starters_userAsPrimary: ["What's the local specialty here?", "I'd like to try something traditional.", "Can you recommend a dish?"], starters_userAsOther: ["Welcome! Are you ready to order, or do you need a few more minutes?", "Can I get you started with something to drink?", "What can I get for you?"] },
        { id: "booking_tour", title: "여행 상품 예약하기 🏞️", description: "현지 투어나 액티비티를 예약하는 상황입니다.", baseContext: "You are a travel agent or tour operator. The user wants to book a tour or activity. Provide information about options, prices, and make the booking. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You want to book a local tour or activity. The user is the travel agent. Inquire about options and make a booking concisely.", starters_userAsPrimary: ["I'm interested in booking a city tour.", "What kind of tours do you offer?", "How much does the [tour name] cost?"], starters_userAsOther: ["Hello! How can I help you plan your activities today?", "We have several tours available. What are you interested in?", "Certainly, let me check the availability for you."] },
        { id: "at_immigration", title: "입국 심사대에서 🛂", description: "공항 입국 심사대에서 심사관의 질문에 답변합니다.", baseContext: "You are an immigration officer. The user is arriving in the country. Ask about the purpose of their visit, length of stay, and check their documents. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are at immigration control upon arriving in a new country. The user is the immigration officer. Answer their questions about your visit concisely.", starters_userAsPrimary: ["Good morning. May I see your passport?", "What is the purpose of your visit?", "How long do you plan to stay?"], starters_userAsOther: ["Next, please. Passport and landing card.", "Good [morning/afternoon]. Welcome to [Country].", "What is the purpose of your visit to [Country]?"] }
    ]},
    { category: "직장 생활 (Work & Business)", items: [
        { id: "job_interview", title: "면접 보기 💼", description: "구직 면접 상황을 연습합니다. 자기소개, 질문 답변 등", baseContext: "You are an interviewer for a job position. The user is a candidate. Ask common interview questions and evaluate their responses in English. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are a candidate at a job interview. The user is the interviewer. Answer questions about your qualifications and experience concisely.", starters_userAsPrimary: ["Tell me about yourself.", "Why are you interested in this position?", "What are your strengths?"], starters_userAsOther: ["Thank you for coming in today. Please, have a seat.", "So, tell me a little bit about yourself.", "Why are you interested in this role at our company?"] },
        { id: "meeting_colleagues", title: "동료와 회의하기 👥", description: "업무 관련 회의에서 의견을 제시하고 토론합니다.", baseContext: "You are a colleague in a business meeting. The user is participating in the meeting. Discuss agenda items, share opinions, and collaborate. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are participating in a business meeting with colleagues. The user is one of your colleagues. Share your opinions and discuss agenda items concisely.", starters_userAsPrimary: ["I'd like to suggest an idea.", "What are your thoughts on this proposal?", "Let's discuss the next steps."], starters_userAsOther: ["Okay team, let's get started. The first item on the agenda is...", "Does anyone have any initial thoughts on this?", "Thanks for sharing, [User's Name]. What does everyone else think?"] },
        { id: "phone_call_business", title: "업무 전화 통화 📞", description: "비즈니스 목적으로 전화를 걸거나 받는 상황입니다.", baseContext: "You are a business professional on a phone call. The user is either initiating or receiving a business call. Handle inquiries, schedule meetings, or discuss projects professionally. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are making or receiving a business phone call. The user is the other party. Discuss professional matters, schedule appointments, or make inquiries concisely.", starters_userAsPrimary: ["Hello, this is [Your Name] from [Your Company].", "May I speak to Mr./Ms. [Name]?", "I'm calling to inquire about..."], starters_userAsOther: ["Good morning, [Company Name], [Your Name] speaking. How can I help you?", "Hello, thank you for calling. This is [Your Name].", "[User's Name] speaking."] },
        { id: "presentation_qna", title: "발표 후 질의응답 🎤", description: "발표를 마친 후 청중의 질문에 답변하는 상황입니다.", baseContext: "You are an audience member after a presentation. The user is the presenter. Ask relevant questions about their presentation. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are the presenter who has just finished a presentation. The user is an audience member asking questions. Answer their questions clearly and concisely.", starters_userAsPrimary: ["Thank you for your presentation. I have a question about...", "Could you elaborate on [specific point]?", "What are the implications of your findings?"], starters_userAsOther: ["Thank you for that insightful presentation. We now have some time for questions.", "Any questions for our speaker?", "Yes, the person in the back?"] },
        { id: "networking_event", title: "네트워킹 행사 🤝", description: "업계 행사에서 새로운 사람들과 교류하며 대화합니다.", baseContext: "You are attending a networking event. The user is also an attendee. Initiate or respond to conversations to build professional connections. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are attending a networking event. The user is another attendee. Engage in conversation to build professional connections concisely.", starters_userAsPrimary: ["Hi, I'm [Your Name]. What brings you to this event?", "That's an interesting point. Could you tell me more?", "It was nice talking to you. Here's my card."], starters_userAsOther: ["Hello! Enjoying the event?", "Hi, I don't think we've met. I'm [Your Name].", "What line of work are you in?"] }
    ]},
    { category: "취미 및 관심사 (Hobbies & Interests)", items: [
        { id: "discussing_movie", title: "영화 이야기하기 🎬", description: "최근에 본 영화나 좋아하는 영화에 대해 친구와 이야기합니다.", baseContext: "You are a friend discussing movies with the user. Talk about recent movies, favorite genres, actors, etc. Encourage the user to express their opinions in English. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are discussing movies with a friend (the user). Share your opinions about movies, genres, actors, etc. concisely.", starters_userAsPrimary: ["Have you seen any good movies lately?", "What's your favorite type of movie?", "I recently watched [Movie Title]..."], starters_userAsOther: ["So, any new movies you'd recommend?", "I'm looking for a good movie to watch, any ideas?", "What did you think of [Movie Title]?"] },
        { id: "talking_about_music", title: "음악 취향 공유하기 🎶", description: "좋아하는 음악 장르, 가수, 노래에 대해 이야기 나눕니다.", baseContext: "You are a friend talking about music. Discuss favorite genres, artists, songs, concerts, etc. Help the user share their musical tastes in English. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are talking about music with a friend (the user). Share your musical tastes, favorite artists, songs, etc. concisely.", starters_userAsPrimary: ["What kind of music do you like?", "Who's your favorite singer?", "Have you heard the new song by [Artist]?"], starters_userAsOther: ["I'm always looking for new music. Any recommendations?", "What have you been listening to lately?", "Do you like [Genre/Artist]?"] },
        { id: "discussing_books", title: "책에 대해 대화하기 📚", description: "읽은 책이나 좋아하는 작가, 장르에 대해 이야기합니다.", baseContext: "You are a fellow book lover. The user wants to discuss books they've read, favorite authors, or genres. Share your thoughts and ask them about theirs. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are discussing books with a fellow book lover (the user). Talk about books you've read, favorite authors, or genres concisely.", starters_userAsPrimary: ["What are you reading currently?", "Do you have a favorite author?", "I just finished a great book called..."], starters_userAsOther: ["Read any good books lately?", "I'm looking for a new book. Any suggestions?", "What kind of books do you usually enjoy?"] },
        { id: "talking_about_sports", title: "스포츠 이야기하기 ⚽", description: "좋아하는 스포츠, 팀, 선수에 대해 이야기합니다.", baseContext: "You are a sports enthusiast. The user wants to talk about sports. Discuss favorite sports, teams, players, recent games, etc. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are talking about sports with an enthusiast (the user). Discuss your favorite sports, teams, players, or recent games concisely.", starters_userAsPrimary: ["Did you watch the game last night?", "Who's your favorite team?", "I love playing [sport]."], starters_userAsOther: ["That was some game last night, wasn't it?", "Are you a fan of [Sport/Team]?", "What sports do you follow?"] }
    ]},
    { category: "사교 활동 (Socializing)", items: [
        { id: "meeting_new_people", title: "새로운 사람과 스몰톡 👋", description: "파티나 모임에서 처음 만난 사람과 가벼운 대화를 나눕니다.", baseContext: "You are someone the user has just met at a social event. Engage in small talk, ask about their interests, job, etc., to help them practice initiating conversations with new people. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You have just met someone (the user) at a social event. Engage in small talk, share your interests, or ask about theirs concisely.", starters_userAsPrimary: ["Hi, I'm [Your Name]. Nice to meet you.", "So, what do you do for a living?", "Are you enjoying the event?"], starters_userAsOther: ["Hello! I don't think we've met. I'm [Your Name].", "Great event, isn't it?", "Hi there, mind if I join you?"] },
        { id: "inviting_friend", title: "친구 초대하기 (식사, 영화 등) 📧", description: "친구에게 식사나 영화 관람 등을 제안하고 약속을 잡습니다.", baseContext: "You are a friend of the user. The user wants to invite you out for a meal, movie, or another activity. Respond to their invitation, discuss plans, and confirm details. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You want to invite your friend (the user) for an activity. Make an invitation, suggest plans, and confirm details concisely.", starters_userAsPrimary: ["Are you free to grab dinner on Friday?", "I was wondering if you'd like to see a movie with me.", "Let's hang out sometime next week."], starters_userAsOther: ["Hey, what are you up to later?", "I was thinking of [activity], want to join?", "We should get together soon."] },
        { id: "accepting_declining_invitation", title: "초대 수락/거절하기 ✅❌", description: "친구의 초대에 대해 수락하거나 정중히 거절하는 방법을 연습합니다.", baseContext: "You have invited the user to an event. The user will practice accepting or declining your invitation politely. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You have been invited to an event by the user. Practice accepting or declining the invitation politely and concisely.", starters_userAsPrimary: ["Thanks for inviting me! I'd love to come.", "That sounds great, but I'm afraid I have other plans.", "I appreciate the invitation, but I don't think I can make it."], starters_userAsOther: ["I'm having a get-together on Saturday, would you like to come?", "Want to catch a movie this weekend?", "I'm planning a [event], hope you can make it!"] }
    ]},
    { category: "문제 해결 및 요청 (Problem Solving & Requests)", items: [
        { id: "returning_item", title: "물건 환불/교환하기 🛍️", description: "상점에서 구매한 물건을 환불하거나 교환 요청하는 상황입니다.", baseContext: "You are a store clerk. The user wants to return or exchange an item they purchased. Ask for the reason, receipt, and guide them through the store's policy. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You want to return or exchange an item at a store. The user is the store clerk. Explain your reason and follow the process concisely.", starters_userAsPrimary: ["I'd like to return this item, please.", "Can I exchange this for a different size?", "There's a problem with this product I bought."], starters_userAsOther: ["Hi, how can I help you today?", "Do you have your receipt?", "What seems to be the problem with the item?"] },
        { id: "tech_support", title: "기술 지원 문의하기 💻", description: "제품 사용 중 문제가 발생하여 기술 지원팀에 문의합니다.", baseContext: "You are a technical support agent. The user is calling about an issue with a product or service. Help them troubleshoot the problem or escalate the issue. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are calling technical support for an issue with a product or service. The user is the support agent. Describe your problem and seek assistance concisely.", starters_userAsPrimary: ["I'm having trouble with my [product/service].", "My internet isn't working.", "Could you help me fix this error?"], starters_userAsOther: ["Thank you for calling Tech Support, my name is [Your Name]. How can I help you?", "Could you please describe the issue you're experiencing?", "Have you tried restarting your device?"] },
        { id: "making_complaint", title: "불만 제기하기 (호텔, 식당 등) 😠", description: "서비스나 제품에 대한 불만을 정중하게 표현합니다.", baseContext: "You are a manager or customer service representative. The user has a complaint about a service or product. Listen to their concerns and try to resolve the issue. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You have a complaint about a service or product. The user is the manager or customer service representative. Express your dissatisfaction politely and concisely.", starters_userAsPrimary: ["I'm afraid I have a complaint about...", "I'm not satisfied with the service I received.", "Could I speak to the manager, please?"], starters_userAsOther: ["I understand you have a concern. Please tell me what happened.", "I'm sorry to hear you're not satisfied. How can I make things right?", "Thank you for bringing this to my attention."] }
    ]},
    { category: "건강 및 의료 (Health & Medical)", items: [
        { id: "hospital_visit", title: "병원 방문 (일반 진료) 🏥", description: "의사나 간호사에게 증상을 설명하고 진료 관련 대화를 나눕니다. AI는 의료진 역할을 합니다.",
          baseContext: "You are a doctor or nurse at a hospital. The user is a patient explaining their symptoms. Ask clarifying questions ONE AT A TIME. Keep responses concise (1-2 sentences) and professional. Do not ask many questions at once. Do not ask questions you've already received answers for.",
          baseContext_swapped: "You are a patient visiting a doctor/nurse (the user). Describe your symptoms or ask for advice concisely. Respond to one question at a time.",
          starters_userAsPrimary: ["I'd like to see a doctor. I'm not feeling well.", "I have a persistent cough and a sore throat.", "I think I might have sprained my ankle."],
          starters_userAsOther: ["Hello, what seems to be the problem today?", "Good morning. How can I help you?", "Please tell me what's bothering you."] },
        { id: "dentist_visit", title: "치과 방문 🦷", description: "치과 의사나 위생사에게 치아 문제를 설명하거나 정기 검진 관련 대화를 합니다. AI는 치과 의료진 역할을 합니다.",
          baseContext: "You are a dentist or dental hygienist. The user is a patient. Ask about their dental issue or needs. Keep questions focused and concise (1-2 sentences per turn). Ask ONE question at a time. Do not ask questions you've already received answers for.",
          baseContext_swapped: "You are a patient at a dental clinic. The user is the dentist/hygienist. Explain your dental concern or reason for visit concisely. Respond to one question at a time.",
          starters_userAsPrimary: ["I have a toothache, and I'd like to make an appointment.", "I'm here for my 6-month check-up and cleaning.", "This tooth has been really sensitive to cold lately."],
          starters_userAsOther: ["Hi, welcome to our dental clinic. How can I help you today?", "What brings you in to see us?", "Are you here for a check-up or a specific issue?"] }
    ]},
    { category: "특별한 상황 (Special Occasions)", items: [
        { id: "birthday_party", title: "생일 파티 대화 🎉", description: "생일 축하 메시지를 전하고 파티에서 대화합니다.", baseContext: "You are a guest at a birthday party. The user is also a guest or the birthday person. Engage in light conversation, offer good wishes. Respond concisely (1-2 sentences) and one question at a time. Do not ask questions you've already received answers for.", baseContext_swapped:"You are at a birthday party. The user is another guest or the birthday person. Engage in conversation and offer good wishes concisely.", starters_userAsPrimary: ["Happy birthday!", "This is a great party!", "How are you enjoying your special day?"], starters_userAsOther: ["Thanks for coming to my party!", "So glad you could make it!", "Are you having a good time?"] },
        { id: "congratulating_someone", title: "축하 표현하기 🥳", description: "다른 사람의 좋은 일(승진, 졸업 등)을 축하합니다.", baseContext: "You are a friend or colleague of the user. The user wants to congratulate you or someone else on an achievement. Respond appropriately and concisely (1-2 sentences). Do not ask questions you've already received answers for.", baseContext_swapped:"You want to congratulate a friend or colleague (the user) on an achievement. Express your congratulations concisely.", starters_userAsPrimary: ["Congratulations on your promotion!", "That's fantastic news! Well done.", "I'm so happy for you!"], starters_userAsOther: ["Thank you so much!", "I really appreciate that.", "It means a lot to hear that from you."] }
    ]},
    { category: "사용자 설정", isCustomCategory: true, items: [
        { id: "custom", title: "직접 입력 ✨", description: "연습하고 싶은 상황이나 대화 주제를 아래에 자세히 입력해주세요.", baseContext: "", baseContext_swapped: "", starters_userAsPrimary: ["Let's talk about [your topic].", "I want to practice discussing [your situation].", "Can we simulate a conversation about [your scenario]?"], starters_userAsOther: ["Okay, I'm ready for the custom scenario you described. What's my first line?", "I understand the custom scenario. How should I begin as the other person?", "Let's start the custom role-play. What's my role according to your description?"] }
    ]}
];
